/** Generate a self-contained HTML report from a VibeReport. */

import type { CheckResult, VibeReport } from "../types.js";

function esc(s: string): string {
	return s
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function gradeColor(grade: string): string {
	return (
		{ A: "#22c55e", B: "#84cc16", C: "#eab308", D: "#f97316", F: "#ef4444" }[
			grade
		] || "#6b7280"
	);
}

function checkCard(c: CheckResult): string {
	const skipped = (c.details as any).skipped;
	const color = skipped ? "#6b7280" : gradeColor(c.grade);
	const detail = Object.entries(c.details)
		.filter(([k]) => k !== "skipped" && k !== "reason")
		.map(
			([k, v]) =>
				`<span class="d-item"><strong>${esc(k)}</strong>: ${typeof v === "object" ? JSON.stringify(v) : v}</span>`,
		)
		.join("");
	const issueCount = c.issues.length;
	const issueHtml = c.issues
		.slice(0, 10)
		.map(
			(i) =>
				`<div class="issue ${i.severity}"><span class="i-sev">${i.severity}</span>${i.file ? `<span class="i-file">${esc(i.file)}${i.line ? ":" + i.line : ""}</span>` : ""}${esc(i.message)}</div>`,
		)
		.join("");
	const moreHtml =
		issueCount > 10
			? `<div class="issue info">...and ${issueCount - 10} more</div>`
			: "";

	return `<div class="card">
  <div class="card-head">
    <span class="card-grade" style="color:${color}">${skipped ? "—" : c.grade}</span>
    <div class="card-info">
      <strong>${esc(c.name)}</strong>
      <span class="card-score">${skipped ? "skipped" : c.score + "/100"}</span>
    </div>
    <span class="card-ms">${c.duration}ms</span>
  </div>
  ${detail ? `<div class="card-details">${detail}</div>` : ""}
  ${issueHtml ? `<div class="card-issues">${issueHtml}${moreHtml}</div>` : ""}
</div>`;
}

export function generateHTML(report: VibeReport): string {
	const gc = gradeColor(report.grade);
	const checksHtml = report.checks.map(checkCard).join("\n");

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Vibe Check — ${report.meta.cwd.split("/").pop()}</title>
<style>
:root{--bg:#09090b;--card:#141418;--border:#23232a;--text:#e5e5e5;--muted:#6b7280;--pass:#22c55e;--fail:#ef4444;--warn:#eab308}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:"Inter",system-ui,sans-serif;background:var(--bg);color:var(--text);padding:2rem;max-width:720px;margin:0 auto;line-height:1.5}
h1{font-size:1.4rem;font-weight:700;margin-bottom:0.2rem}
.meta{color:var(--muted);font-size:0.8rem;margin-bottom:2rem}
.hero{text-align:center;padding:2rem;border-radius:1rem;margin-bottom:2rem;border:1px solid var(--border);background:var(--card)}
.hero-grade{font-size:5rem;font-weight:900;letter-spacing:-0.05em}
.hero-score{font-size:1.2rem;font-weight:600;margin-top:0.2rem}
.hero-label{color:var(--muted);font-size:0.8rem;margin-top:0.4rem}
.stack{display:flex;gap:0.5rem;flex-wrap:wrap;margin-bottom:1.5rem}
.stack span{background:var(--card);border:1px solid var(--border);padding:0.2rem 0.6rem;border-radius:9999px;font-size:0.7rem;color:var(--muted)}
.card{background:var(--card);border:1px solid var(--border);border-radius:0.75rem;margin-bottom:0.6rem;overflow:hidden}
.card-head{display:flex;align-items:center;gap:0.75rem;padding:0.7rem 1rem}
.card-grade{font-size:1.4rem;font-weight:900;width:2rem;text-align:center}
.card-info{flex:1}
.card-info strong{font-size:0.9rem;text-transform:capitalize}
.card-score{display:block;font-size:0.75rem;color:var(--muted)}
.card-ms{font-size:0.65rem;color:var(--muted)}
.card-details{padding:0.3rem 1rem 0.5rem 3.5rem;font-size:0.75rem;color:var(--muted);display:flex;gap:1rem;flex-wrap:wrap}
.d-item strong{color:var(--text)}
.card-issues{border-top:1px solid var(--border);padding:0.4rem 1rem 0.5rem 3.5rem}
.issue{font-size:0.72rem;font-family:monospace;padding:0.15rem 0;display:flex;gap:0.5rem;align-items:baseline}
.i-sev{font-weight:700;font-size:0.6rem;text-transform:uppercase;min-width:3.5rem}
.issue.error .i-sev{color:var(--fail)}
.issue.warning .i-sev{color:var(--warn)}
.issue.info .i-sev{color:var(--muted)}
.i-file{color:var(--muted)}
.footer{text-align:center;color:var(--muted);font-size:0.65rem;margin-top:2rem;padding-top:1rem;border-top:1px solid var(--border)}
</style>
</head>
<body>
<h1>vibe-check</h1>
<p class="meta">${esc(report.meta.cwd)} &mdash; ${report.timestamp}</p>

<div class="hero">
  <div class="hero-grade" style="color:${gc}">${report.grade}</div>
  <div class="hero-score" style="color:${gc}">${report.score}/100</div>
  <div class="hero-label">${report.checks.filter((c) => !(c.details as any).skipped).length} checks &middot; ${report.meta.duration}ms &middot; ${report.meta.stack.language}/${report.meta.stack.framework}</div>
</div>

<div class="stack">
  ${Object.entries(report.meta.stack)
		.map(([k, v]) => `<span>${k}: ${v}</span>`)
		.join("")}
</div>

${checksHtml}

<div class="footer">
  Generated by <a href="https://github.com/freeappstore-online/vibe-check" style="color:var(--muted)">vibe-check</a> v${report.version}
</div>
</body></html>`;
}
